name: Автоматическое ревью PR с Ollama

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  ollama_review:
    runs-on: ubuntu-latest
    name: Ollama Code Review
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ollama
        uses: ollama/setup-ollama@v1

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Pull CodeLlama Model
        run: ollama pull codellama

      - name: Review Changes
        run: |
          # Получаем список измененных файлов
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          
          # Создаем комментарий для PR
          COMMENT=""
          
          for file in $FILES; do
            if [[ -f "$file" ]]; then
              echo "Reviewing $file..."
              REVIEW=$(cat "$file" | ollama run codellama "Review this code and provide suggestions for improvements. Focus on: 
              1. Code quality
              2. Potential bugs
              3. Security issues
              4. Performance improvements
              Be concise and specific.")
              
              COMMENT="$COMMENT\n\n### Review for \`$file\`:\n$REVIEW"
            fi
          done
          
          echo "$COMMENT" > review.txt

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: review
            });
