name: Автоматическое ревью PR с Ollama

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      
jobs:
  ollama_review:
    runs-on: ubuntu-latest
    name: Ollama Code Review
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ollama Code Review
        uses: zakerby/ollama-code-review@v0.0.2
        with:
          llm-model: 'codellama'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
